trigger:
- main
resources:
- repo: self

variables:
  imageRepository: 'microservices'
  containerRegistry: 'fahelocr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  acrsecret: k8sexampleacrauth

stages:
- stage: Build_Docker
  displayName: Build Docker and Push in Container Registry
  jobs:
  - job: Build
    displayName: Build Docker
    pool:
        name: Default
        vmImage: '$(vmImageName)'
        demands:
        - agent.name -equals pc-fahelo
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'containerRegistryServiceConnection'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      displayName: publish the manifest k8s files to the pipeline
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/k8s'
        artifact: 'manifests'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build_Docker
  jobs:
    - job: Deploy
      displayName: Deploy to AKS
      pool:
        name: Default
        vmImage: '$(vmImageName)'
        demands:
        - agent.name -equals pc-fahelo
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: disponibilizar manifiesto k8s
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          targetPath: '$(Pipeline.Workspace)/manifests'
      - task: KubernetesManifest@0
        displayName: crear secreto para acceder a ACR
        inputs:
          action: 'createSecret'
          kubernetesServiceConnection: 'k8sServiceConnection'
          namespace: 'default'
          secretType: 'dockerRegistry'
          secretName: '$(acrsecret)'
          dockerRegistryEndpoint: 'containerRegistryServiceConnection'
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'k8sServiceConnection'
          namespace: 'default'
          manifests: |
            $(Pipeline.Workspace)/manifests/deployment.yml
            $(Pipeline.Workspace)/manifests/service.yml
          containers: '$(containerRegistry)/$(imageRepository):$(tag)'''
          imagePullSecrets: '$(acrsecret)'
          rolloutStatusTimeout: '120'
          
      