apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-microservice
  template:
    metadata:
      labels:
        app: demo-microservice
    spec:
      containers:
        - name: service-app
          image: service-app:latest
          imagePullPolicy: Never
