apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-microservice
  template:
    metadata:
      labels:
        app: service-microservice
    spec:
      containers:
        - name: microservices
          image: microservices:latest
          imagePullPolicy: Never
