apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
        - name: microservices
          image: fahelocr.azurecr.io/microservices:56
          imagePullPolicy: Never
