apiVersion: v1
kind: Service
metadata:
  name: service-microservice
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: service-microservice
  type: LoadBalancer
